### ISSUE TITLE
Unable to get the whole shebang working with 1 line...

### ISSUE THREAD

**Issue by dabeeeenster** [agius/HackerMusic#3]
I've got the app running, but I need to break up the command:

```
icecast -b -c icecast.xml thin -C config.yml -R rackup_hm.ru start ruby streamer.rb >logs/streamer.log
```

Into 2:

```
icecast -b -c icecast.xml thin -C config.yml -R rackup_hm.ru 
```

and

```
ruby streamer.rb >logs/streamer.log
```

In order to have the app push songs to the icecast server. Not sure why this is, and I can't find any logs to suggest what the problem is! 

Also, in the docs, I think there is an error in that line - I had to use a capital C in the thin command: 

```
thin -c config.yml 
```

became 
    thin -C config.yml

**Comment by bkudria** [comment]
Indeed, you are correct on both counts, with the clarification that it needs to be split into 3 lines, not 2. I've fixed the formatting on the README accordingly. Thanks!
