### ISSUE TITLE
no such file to load -- tagfile/tagfile (LoadError)

### ISSUE THREAD

**Issue by neoice** [agius/HackerMusic#4]
```
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- tagfile/tagfile (LoadError)
from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from ./HM_Indexer.rb:2
from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from indexer.rb:3
```

I've replicated the issue on OSX 10.5 PPC and Gentoo i686, both running Ruby 1.8.7 and Rubygems 1.3.6. I've tried everything I know (which isnt much) to no avail. on both systems, I needed to add "require 'yaml'" to a few files, so I'm not sure how up-to-date the code and readme are. I'd _really_ like to get this working on my old G5, but I'd settle for running it in a Linux VM. I'm not sure what else to try other than reinstalling everything for a third time.

**Comment by ghost** [comment]
I'm in the exact same boat.  OS X 10.6 and I finally got everything to install but taglib.  I also had to add `require 'yaml'` to setup.rb to get it to run.  I continually get an error when trying to install taglib.  I hope this is what it's complaining about.

**Comment by neoice** [comment]
Just for reference, did you have a huge problem getting this far? I tried several variations of system Ruby (not so good on 10.5), Macports and rubyosx before I could even get this far... I think the issue may be that taglib has completely changed. There's taglib, rtaglib and ruby-taglib. One looks abandoned and one looks like a successor. I don't know enough to delve past that.

**Comment by ghost** [comment]
I just had a hell of a time getting cmake to install (issue fixed not less than half an hour ago http://trac.macports.org/ticket/24399) which was required by taglib.  I am at the point where I need to run `ruby indexer.rb`

This is my output
`

$ ruby indexer.rb 
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- tagfile/tagfile (LoadError)
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./HM_Indexer.rb:2
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from indexer.rb:3
Basilisk:hackermusic TLK$ ruby indexer.rb 
/opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- tagfile/tagfile (LoadError)
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./HM_Indexer.rb:2
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from indexer.rb:3
`

**Comment by ghost** [comment]
well it looks like crap but you get the idea.  PRETTY MUCH the same issue here.  The install is a little wonky like `sudo gem update –system` should be `sudo gem update –-system`

**Comment by ghost** [comment]
`require 'tagfile/tagfile'` is the problem i am seeing.  I know I have installed taglib and even `sudo gem install rtaglib` which http://rtaglib.rubyforge.org/ recommends.  Sigh.  As soon as I can get Ruby to figure out `require 'tagfile/tagfile'` I feel all the problems will be fixed.

**Comment by neoice** [comment]
it looks like this project might be dead.
